### PR TITLE
Add propagate tags

### PR DESCRIPTION
**Pull request by SaiPrasannaGopularam**
# Changes
- Add tag propagation that are associated with ecs service to the tasks

### CODE REVIEW

**Comment by SaiPrasannaGopularam** [comment]
Terraform plan on payments:
```Terraform will perform the following actions:

  # module.payments.data.aws_iam_policy_document.task_execution_role_policy will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "task_execution_role_policy" {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "secretsmanager:GetSecretValue",
            ]
          + effect    = "Allow"
          + resources = [
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:Masteraccount-dev-8ZyRaa",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/AMPLITUDE_API_KEY-7zF6bA",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/APPSFLYER_AUTHENTICATION-OD5tlE",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/BRAINTREE_MERCHANT_ID-0B1HUD",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/BRAINTREE_PRIVATE_KEY-0B1HUD",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/BRAINTREE_PUBLIC_KEY-NFSVWE",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/ITERABLE_RK_API_KEY-nBUbYB",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/ITUNES_SECRET-zBRpxC",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/PAYPAL_PASSWORD-YMM9be",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/PAYPAL_SIGNATURE-nBUbYB",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/PAYPAL_USERNAME-0B1HUD",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/STATIC_ASSETS_ORIGIN_IDENTITY-bDLm3C",
              + "arn:aws:secretsmanager:us-east-1:332913666507:secret:runkeeper-dockerhub-secret-T6X3oj",
            ]
        }
      + statement {
          + actions   = [
              + "kms:Decrypt",
            ]
          + effect    = "Allow"
          + resources = [
              + "arn:aws:kms:us-east-1:332913666507:key/e595a96f-8ec9-4677-89a2-da13c6d2e197",
            ]
        }
      + statement {
          + actions   = [
              + "ecs:DescribeTasks",
              + "ecs:ExecuteCommand",
            ]
          + effect    = "Allow"
          + resources = [
              + (known after apply),
            ]
        }
    }

  # module.payments.aws_ecs_service.service will be updated in-place
  ~ resource "aws_ecs_service" "service" {
        id                                 = "arn:aws:ecs:us-east-1:332913666507:service/ue1dev-runkeeper-services/payments-dev-api-service"
        name                               = "payments-dev-api-service"
      ~ propagate_tags                     = "NONE" -> "SERVICE"
        tags                               = {
            "Application"      = "payments-dev"
            "Env"              = "dev"
            "TerraformManaged" = "true"
        }
      ~ task_definition                    = "arn:aws:ecs:us-east-1:332913666507:task-definition/payments-dev-api:84" -> (known after apply)
        # (14 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }

  # module.payments.aws_ecs_task_definition.task must be replaced
-/+ resource "aws_ecs_task_definition" "task" {
      ~ arn                      = "arn:aws:ecs:us-east-1:332913666507:task-definition/payments-dev-api:84" -> (known after apply)
      ~ arn_without_revision     = "arn:aws:ecs:us-east-1:332913666507:task-definition/payments-dev-api" -> (known after apply)
      ~ container_definitions    = jsonencode(
          ~ [
              ~ {
                  ~ image                 = "fitnesskeeper/payments:2a6628ebf058efb519d3431b4b4b31a126c6867c" -> "fitnesskeeper/payments:285d4c2acf01f53e4aaae6c0501d93b7de095b6b"
                    name                  = "payments-dev-api"
                    # (12 unchanged attributes hidden)
                },
            ] # forces replacement
        )
      ~ id                       = "payments-dev-api" -> (known after apply)
      ~ revision                 = 84 -> (known after apply)
        tags                     = {
            "Application"      = "payments-dev"
            "Env"              = "dev"
            "TerraformManaged" = "true"
        }
        # (9 unchanged attributes hidden)
    }

  # module.payments.aws_iam_role_policy.task_execution_role_policy will be updated in-place
  ~ resource "aws_iam_role_policy" "task_execution_role_policy" {
        id     = "payments-dev-api-ecsTaskExecutionRole:payments-dev-api-ecs-task-execution-role-policy"
        name   = "payments-dev-api-ecs-task-execution-role-policy"
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "secretsmanager:GetSecretValue"
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:runkeeper-dockerhub-secret-T6X3oj",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/STATIC_ASSETS_ORIGIN_IDENTITY-bDLm3C",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/PAYPAL_USERNAME-0B1HUD",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/PAYPAL_SIGNATURE-nBUbYB",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/PAYPAL_PASSWORD-YMM9be",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/ITUNES_SECRET-zBRpxC",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/ITERABLE_RK_API_KEY-nBUbYB",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/BRAINTREE_PUBLIC_KEY-NFSVWE",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/BRAINTREE_PRIVATE_KEY-0B1HUD",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/BRAINTREE_MERCHANT_ID-0B1HUD",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/APPSFLYER_AUTHENTICATION-OD5tlE",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:payments/dev/env-vars/AMPLITUDE_API_KEY-7zF6bA",
                          - "arn:aws:secretsmanager:us-east-1:332913666507:secret:Masteraccount-dev-8ZyRaa",
                        ]
                      - Sid      = ""
                    },
                  - {
                      - Action   = "kms:Decrypt"
                      - Effect   = "Allow"
                      - Resource = "arn:aws:kms:us-east-1:332913666507:key/e595a96f-8ec9-4677-89a2-da13c6d2e197"
                      - Sid      = ""
                    },
                  - {
                      - Action   = [
                          - "ecs:ExecuteCommand",
                          - "ecs:DescribeTasks",
                        ]
                      - Effect   = "Allow"
                      - Resource = "arn:aws:ecs:us-east-1:332913666507:task-definition/payments-dev-api:84"
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 2 to change, 1 to destroy.

**Review by automationforthepeople — APPROVED** [review]

**Comment by automationforthepeople** [comment]
@SaiPrasannaGopularam did you run terraform-cleaner on this module by chance?

**Comment by SaiPrasannaGopularam** [comment]
> @SaiPrasannaGopularam did you run terraform-cleaner on this module by chance?

No! I will make another PR if I catch any

**Comment by SaiPrasannaGopularam** [comment]
> @SaiPrasannaGopularam did you run terraform-cleaner on this module by chance?

Found 1 unused variable `docker_port_mappings` using terraform-cleaner

**Pull request merged**
